# Включить автоисправление
fix = true

# Длина строка
line-length = 100

# Исключаем тесты из проверок
exclude = ["tests"]

# Выбрать правила - не слишком строгие, но полезные
lint.select = [
    "E",  # стандартные ошибки синтаксиса
    "F",  # pyflakes (неиспользуемые импорты и т.д.)
    "I",  # isort (сортировка импортов)
    "UP", # улучшения синтаксиса под новые версии Python
    "B",  # обнаружение потенциальных багов
]
# Игнорировать некоторые слишком строгие правила
lint.ignore = [
    "E501", # длина строки
]
# Исключить ненужные директории
lint.exclude = [".git", "__pycache__", "venv", ".venv", "tests"]

# Настройки форматирования
format.quote-style = "double"
format.indent-style = "space"
format.line-ending = "auto"
format.exclude = ["tests"]
